[package]
name = "cursor-pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.6.0"
bytemuck = "1.7.3"
glutin = "0.28.0"
glow = "0.11.2"
glam = "0.20.2"
