[package]
name = "cursor-pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.7.3"
bevy_ecs = "0.6.0"
gl = "0.14.0"
glam = "0.20.2"
glutin = "0.28.0"
